version: "3.7"

services: 
  database: 
    image: postgres
    container_name: "database_iclinic"
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=iclinic
      - POSTGRES_DB=iclinic
    volumes: 
      - pgdata:/data/postgres
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: "redis_iclinic"
    restart: always
    ports: 
      - 6379:6379
    networks:
      - app-network
      
  app:
    build: .
    container_name: iclinic
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes: 
  pgdata:
    driver: local